### ISSUE TITLE
Soundtrack of Counter-Strike 2 not detected?

### ISSUE THREAD

**Issue by woctezuma** [Citrinate/FreePackages#14]
It seems that the [soundtrack of Counter-Strike 2](https://store.steampowered.com/app/2678630/CounterStrike_2_Soundtrack/) evaded the detection.
Maybe I should be more patient, but it seems not to be picked even though I only skip demos.

**Comment by Citrinate** [comment]
I noticed this also.  This is a limitation of the plugin.

Sometimes the product info on apps or packages is completely or partially hidden, and a token is needed to see the hidden info.  In this case, the "IsFreeApp" flag is hidden, and so the plugin ignored it because it couldn't see that it was free.

SteamDB was able to determine that the soundtrack was free due to the large number of people who use some sort of [token dumper](https://steamdb.info/tokendumper/) tool.

**Comment by woctezuma** [comment]
I see. Thank you for the explanation!

**Comment by woctezuma** [comment]
I don't know if it happened again for [`Turner - Soundtrack`](https://steamdb.info/sub/115938/), but it may as some bots have it, but others don't have it.

**Comment by Citrinate** [comment]
I don't notice an issue with that one.  Maybe your filters excluded it?  That's an older soundtrack that's considered `DLC` and not `Music`
