### ISSUE TITLE
Clarification of the README

### ISSUE THREAD

**Issue by woctezuma** [Citrinate/FreePackages#2]
>  Since PICs doesn't show changes that happened before a certain time, the plugin may not discover all previously released free packages.

Alright, this makes sense. The plugin listens for changes, it won't check what happens a long time before it was first used.

> It's also possible to miss newly released free packages if your bot is logged out for extended periods of time.

What do you mean? Would you mind clarifying this sentence?

Is it about free packages which would become unavailable before the bot logs in? For instance, demos in Steam festivals?

Other than that, the plugin should be able to retrieve all of the free packages since the last `Changenumber`, and queue them appropriately to deal with the rate-limit. There is no reason to miss a free package if it is still available, right?

**Comment by Citrinate** [comment]
> Other than that, the plugin should be able to retrieve all of the free packages since the last `Changenumber`, and queue them appropriately to deal with the rate-limit, right?

Not if the `ChangeNumber` is too old.  If the `ChangeNumber` is too old and we ask Steam for all changes since then, then Steam will return nothing.  You can use the plugin's `GetChangesSince` IPC endpoint to mess around and see what Steam returns for different change numbers.

What's considered "too old" is sort of random.  Most of the time we can see changes that are 12-16 hours old.  Meaning if you log in every 12 hours you shouldn't miss anything.

Occasionally there will be a single big change that effects thousands of items, such as [this one](https://steamdb.info/changelist/20333525/).  When that change happened, I wasn't able to see any changes that happened before it, even though the changes I wanted to look at were less than 15 minutes old at the time.

**Comment by woctezuma** [comment]
Thank you for all these pieces of info!
