### ISSUE TITLE
Free Packages Importer userscript "Failed to add packages."

### ISSUE THREAD

**Issue by renatamer** [Citrinate/FreePackages#39]
Current version of the userscript results in "Failed to add packages." while adding packages from [SteamDB's Free Packages page](https://steamdb.info/freepackages/).

Using Tampermonkey on Firefox.

**Comment by woctezuma** [comment]
I cannot reproduce your issue.

![Picture](https://i.imgur.com/qZarKKv.png)

**Comment by Citrinate** [comment]
There should be an error logged to the developer console (Tools > Web Developer > Web Developer Tools or use the keyboard shortcut Ctrl + Shift + I), can you post that here?  ASF's logs might also have something relevant.

**Comment by renatamer** [comment]
Hey there, thanks for the assistance!

ASF's logs showed nothing out of the ordinary, but here's the output of the developer console:

> Object { readyState: 4, responseHeaders: "content-length: 0\r\ndate: Thu, 27 Jun 2024 06:36:11 GMT\r\n", finalUrl: "http://localhost:1242/Api/FreePackages/ASF/QueueLicenses", status: 404, statusText: "Not Found", DONE: 4, HEADERS_RECEIVED: 2, LOADING: 3, OPENED: 1, UNSENT: 0, … }
​
DONE: 4
​
HEADERS_RECEIVED: 2
​
LOADING: 3
​
OPENED: 1
​
RESPONSE_TYPE_ARRAYBUFFER: "arraybuffer"
​
RESPONSE_TYPE_BLOB: "blob"
​
RESPONSE_TYPE_DOCUMENT: "document"
​
RESPONSE_TYPE_JSON: "json"
​
RESPONSE_TYPE_STREAM: "stream"
​
RESPONSE_TYPE_TEXT: "text"
​
UNSENT: 0
​
finalUrl: "http://localhost:1242/Api/FreePackages/ASF/QueueLicenses"
​
readyState: 4
​
responseHeaders: "content-length: 0\r\ndate: Thu, 27 Jun 2024 06:36:11 GMT\r\n"
​
status: 404
​
statusText: "Not Found"

**Comment by woctezuma** [comment]
Error 404 Page Not Found. Maybe ensure IPC works.

**Comment by Citrinate** [comment]
What ASF version and plugin version are you using?

I can only think of two explanations: either you're using an old version of the plugin (pre V1.1.0), or something is blocking requests to that url.

If you are using the latest plugin version, then this sounds like some technical networking problem specific to whatever computer setup you have, and I can't help with that.  Though maybe it's being blocked because of the amount of data being sent (assuming you're trying to import everything on SteamDB, which can be more than 25,000 packages).  You can test this by running this code from the developer console on SteamDB's free packages page after it's done loading:

```
document.querySelectorAll(".package:not(:nth-child(-n+11))").forEach(e => e.remove())
```

This will hide all but the first 10 free packages on SteamDB, after which try adding only those 10 packages using the userscript and see if that works.

**Comment by renatamer** [comment]
I'm using ASF version 6.0.3.4 and FreePackages version 1.5.0.1. 

The code you shared worked! I was able to add those 10 packages.
![imagen](https://github.com/Citrinate/FreePackages/assets/49537750/8cf9d3f7-efb8-4978-aa51-4c103b152c4a)
