### ISSUE TITLE
What about playtests?

### ISSUE THREAD

**Issue by woctezuma** [Citrinate/FreePackages#5]
I see there is commented code about playtests.

https://github.com/Citrinate/FreePackages/blob/8f8f9144e324785fefe64c5314bc88684ce6c592/FreePackages/Handlers/PackageFilter.cs#L79-L88

With the current plugin, what happens to playtests? Are they ignored? Or do they get added to the account?

Is there a difference between playtests which can be instantly added by the user, and playtests which require the user to make a request and wait for a validation from the dev?

I don't see playtests in the category setting. Maybe it would make sense to have a configuration setting for them.

**Comment by Citrinate** [comment]
As of now, I don't see why the plugin couldn't join playtests.  However, playtests are activated differently from apps and subs.  The plugin can't currently do anything with them, and so they're just ignored.

There's an ethical question here, because some playtests have a limited number of slots.  It's unfair to the average Steam user and to developers if a playlist's queue is filled with people using this plugin who likely aren't going to participate in a playtest.

If this plugin ever does support playtests, they'll have their own filter settings and will be disabled by default.

**Comment by woctezuma** [comment]
Thank you for the detailed reply! I understand your stance regarding playtests.

**Comment by woctezuma** [comment]
> There's an ethical question here, because some playtests have a limited number of slots. It's unfair to the average Steam user and to developers if a playlist's queue is filled with people using this plugin who likely aren't going to participate in a playtest.

For info, playtests are not limited by Valve according to:
- this introduction to Barter: https://github.com/bartervg/barter.vg/wiki/Ultimate-Beginners-Guide#steam-playtest
- the official documentation of playtests: https://partner.steamgames.com/doc/features/playtest

**Comment by Citrinate** [comment]
It's good to know that limited testers are selected randomly and not first-come-first-serve.

I am planning on adding this in V1.2.  Plans are still for it to be an opt-in feature, and also for only 1 account to be able to opt-in.
