### ISSUE TITLE
Option to change the pause time

### ISSUE THREAD

**Issue by biast12** [Citrinate/FreePackages#55]
I noticed that steamdb can do around 25/30 packages every 3 min before getting rate-limited, is there any reason why the plugin noly can do 30 packages every 1.5 hours?

I think it would be really useful to have a config option to change the pause time if there isn't something stopping the tool from doing more

**Comment by Citrinate** [comment]
I think you're mistaken about the SteamDB tool letting you activate 25/30 every 3 minutes.  It will usually let you do 30 packages when you first run it, but then after that it'll be only 1 every 3 minutes (or 30 every 1.5 hours).  Those initial 30 packages are because you haven't activated any free packages in at least 1.5 hours.

Just tested it myself to confirm that nothing has changed on Steam's end and that was my experience.

**Comment by biast12** [comment]
Mmmm oh yeah that's my fault, tho i do think how SteamDB does it is really good and would love it as an option for this tool too, as it may take a long time if you need to restart ArchiSteamFarm etc
